name: CI/CD Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run tests
        run: |
          cd kbot
          go test -v ./...
      - name: Run linting
        run: |
          cd kbot
          go vet ./...
          golangci-lint run
  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./kbot
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  update-helm-chart:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Helm chart version
        run: |
          cd kbot/helm
          # Update the chart version
          sed -i 's/version: "0.1.0"/version: "0.1.1"/' Chart.yaml
          sed -i 's/appVersion: "0.1.0"/appVersion: "0.1.1"/' Chart.yaml
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add kbot/helm/Chart.yaml
          git commit -m "Update Helm chart version to 0.1.1"
          git push
  deploy-to-flux:
    needs: update-helm-chart
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Flux manifests
        run: |
          # Update the image tag in Flux manifests
          sed -i 's/tag: latest/tag: ${{ github.sha }}/' tf-test-w7/flux-manifests/apps/kbot/helmrelease.yaml
      - name: Commit and push Flux changes
        run: "git config --local user.email \"action@github.com\"\ngit config --local user.name \"GitHub Action\"\ngit add tf-test-w7/flux-manifests/\ngit commit -m \"Update kbot image tag to ${{ github.sha }}\"\ngit push "
